'use client';

import React, { useState } from 'react';

export const EvidentiaryStandardKey: React.FC = () => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className="border border-[#2A2A2A] bg-[#0E0E0E] p-5 md:p-6 transition-all duration-300">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-2.5">
          <span className="w-2 h-2 rounded-full bg-[#C62828]" />
          <span className="font-mono text-[11px] uppercase tracking-[0.2em] text-[#F5F5F0] font-bold">
            EVIDENTIARY CLASSIFICATION &amp; CITATION STANDARD
          </span>
        </div>

        <button
          type="button"
          onClick={() => setIsExpanded(!isExpanded)}
          className="font-mono text-[11px] text-[#C62828] hover:text-[#E53935] uppercase tracking-[0.15em] font-semibold transition-colors flex items-center gap-1"
        >
          <span>{isExpanded ? '[ COLLAPSE METHODOLOGY − ]' : '[ INSPECT CITATION TIERS + ]'}</span>
        </button>
      </div>

      {/* Primary 3-Tier Badges Strip (Always Visible) */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-4 pt-4 border-t border-[#2A2A2A] font-mono text-[11px]">
        <div className="flex items-center gap-3 p-2.5 border border-[#C62828]/50 bg-[#C62828]/5">
          <span className="font-bold text-[#E53935] text-[12px]">01</span>
          <div>
            <span className="block text-[#E53935] font-bold uppercase tracking-wider text-[10px]">
              TIER 1: PRIMARY ARCHIVE
            </span>
            <span className="text-[#A3A39D] text-[10px]">
              IOR, Hansard, Cabinet Papers &amp; Commissions
            </span>
          </div>
        </div>

        <div className="flex items-center gap-3 p-2.5 border border-[#2A2A2A] bg-[#141414]">
          <span className="font-bold text-[#F5F5F0] text-[12px]">02</span>
          <div>
            <span className="block text-[#F5F5F0] font-bold uppercase tracking-wider text-[10px]">
              TIER 2: PEER-REVIEWED
            </span>
            <span className="text-[#A3A39D] text-[10px]">
              Econometric models &amp; academic historiography
            </span>
          </div>
        </div>

        <div className="flex items-center gap-3 p-2.5 border border-[#2A2A2A] bg-[#0E0E0E]">
          <span className="font-bold text-[#A3A39D] text-[12px]">03</span>
          <div>
            <span className="block text-[#D6D6D0] font-bold uppercase tracking-wider text-[10px]">
              TIER 3: EDITORIAL AUDIT
            </span>
            <span className="text-[#A3A39D] text-[10px]">
              Forensic synthesis &amp; statistical reconciliation
            </span>
          </div>
        </div>
      </div>

      {/* Expanded Explanatory Panel */}
      {isExpanded && (
        <div className="mt-5 pt-4 border-t border-[#2A2A2A] space-y-4 font-serif text-[13px] leading-relaxed text-[#D6D6D0]">
          <p>
            To uphold the highest threshold of historiographical rigor, every datum, dispatch, casualty estimate, and financial statistic in <em>The Imperial Audit</em> is explicitly categorized into one of three evidentiary tiers:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-2 font-mono text-[11px]">
            <div className="space-y-1.5 p-3 border border-[#2A2A2A] bg-[#0A0A0A]">
              <span className="text-[#E53935] font-bold uppercase block tracking-wider text-[10px]">
                1. PRIMARY EVIDENCE (PROVENANCE)
              </span>
              <p className="font-serif text-[12px] text-[#A3A39D] leading-normal">
                Literal, unredacted transcriptions from the India Office Records (IOR) at the British Library, The National Archives (Kew), Hansard Parliamentary Debates, statutory Command Papers, and contemporary vernacular dispatches.
              </p>
            </div>

            <div className="space-y-1.5 p-3 border border-[#2A2A2A] bg-[#0A0A0A]">
              <span className="text-[#F5F5F0] font-bold uppercase block tracking-wider text-[10px]">
                2. SCHOLARLY CONSENSUS
              </span>
              <p className="font-serif text-[12px] text-[#A3A39D] leading-normal">
                Quantitative econometric calculations (e.g., Utsa Patnaik, Columbia University Press) and peer-reviewed historical monographs (e.g., Amartya Sen, Irfan Habib, Angus Maddison) subject to academic cross-examination.
              </p>
            </div>

            <div className="space-y-1.5 p-3 border border-[#2A2A2A] bg-[#0A0A0A]">
              <span className="text-[#D6D6D0] font-bold uppercase block tracking-wider text-[10px]">
                3. FORENSIC AUDIT NOTES
              </span>
              <p className="font-serif text-[12px] text-[#A3A39D] leading-normal">
                Analytical notes generated by this publication where colonial administrative records and nationalist eyewitness registries diverge (such as the Hunter Commission vs. Congress Inquiry casualty figures for Jallianwala Bagh).
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
